---
- name: ensure tor is properly configured
  lineinfile:
    dest: /etc/tor/torrc
    line: "{{ item.key }} {{ item.value }}"
    regexp: "^{{ item.key }}"
    state: present
  with_items:
    - { key: DNSPort, value: 9053 }
    - { key: AutomapHostsOnResolve, value: 1 }
    - { key: AutomapHostsSuffixes, value: ".exit,.onion" }
  notify:
    - restart tor

- name: ensure privoxy is properly configured
  lineinfile:
    dest: /etc/privoxy/config
    line: "{{ item.key }} {{ item.value }}"
    regexp: "^{{ item.key }}"
    state: present
  with_items:
    - { key: forward-socks5t, value: "/ 127.0.0.1:9050 ." }
  notify:
    - restart privoxy

- name: ensure squid request header access is properly configured
  lineinfile:
    dest: /etc/squid3/squid.conf
    line: "{{ item }}"
    regexp: "^{{ item }}$"
    insertbefore: "^#  TAG: reply_header_access"
  with_items:
    - request_header_access Authorization allow all
    - request_header_access Proxy-Authorization allow all
    - request_header_access Cache-Control allow all
    - request_header_access Content-Length allow all
    - request_header_access Content-Type allow all
    - request_header_access Date allow all
    - request_header_access Host allow all
    - request_header_access If-Modified-Since allow all
    - request_header_access Pragma allow all
    - request_header_access Accept allow all
    - request_header_access Accept-Charset allow all
    - request_header_access Accept-Encoding allow all
    - request_header_access Accept-Language allow all
    - request_header_access Connection allow all
    - request_header_access All deny all
  notify:
    - restart squid

- name: ensure squid reply header access is properly configured
  lineinfile:
    dest: /etc/squid3/squid.conf
    line: "{{ item }}"
    regexp: "^{{ item }}$"
    insertbefore: "^#  TAG: reply_header_replace"
  with_items:
    - reply_header_access Allow allow all
    - reply_header_access WWW-Authenticate allow all
    - reply_header_access Proxy-Authenticate allow all
    - reply_header_access Cache-Control allow all
    - reply_header_access Content-Encoding allow all
    - reply_header_access Content-Length allow all
    - reply_header_access Content-Type allow all
    - reply_header_access Date allow all
    - reply_header_access Expires allow all
    - reply_header_access Last-Modified allow all
    - reply_header_access Location allow all
    - reply_header_access Pragma allow all
    - reply_header_access Content-Language allow all
    - reply_header_access Retry-After allow all
    - reply_header_access Title allow all
    - reply_header_access Content-Disposition allow all
    - reply_header_access Connection allow all
    - reply_header_access All deny all
  notify:
    - restart squid

- name: ensure squid is configured to peer with privoxy only
  lineinfile:
    dest: /etc/squid3/squid.conf
    line: "{{ item.key }} {{ item.value }}"
    regexp: "^{{ item.key }}"
    insertbefore: "^#  TAG: cache_peer_domain"
  with_items:
    - { key: cache_peer, value: "localhost parent 8118 0 no-query" }
  notify:
    - restart squid
 
- name: ensureeservices are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - tor
    - dnsmasq
    - privoxy
    - squid3
