---
- name: ensure desired packages packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - dnsmasq
    - privoxy
    - squid
    - tor
