---
- include: prep.yml

- include: docker.yml
  when: mariadb_dockerized_deployment

- include: install.yml
  when: not mariadb_dockerized_deployment

- include: configure.yml
  when: not mariadb_dockerized_deployment 
